if (EXISTS ${OPENCL_ICD_LOADER_HEADERS_DIR}/CL/cl.h)
    if (NOT TARGET OpenCL::Headers)
        message (STATUS "Defining OpenCL::Headers through OPENCL_ICD_LOADER_HEADERS_DIR")
    endif  ()
    add_library (OpenCLHeaders INTERFACE)
    add_library (OpenCL::Headers ALIAS OpenCLHeaders)
    target_include_directories (OpenCLHeaders INTERFACE ${OPENCL_ICD_LOADER_HEADERS_DIR})
else ()
    if (NOT TARGET OpenCL::Headers)
        find_package (OpenCLHeaders REQUIRED)
    endif ()
endif ()

if(CMAKE_VERSION VERSION_LESS 3.7)
    add_library(OpenCL_lib INTERFACE)
    target_include_directories(OpenCL_lib INTERFACE ${OpenCL_INCLUDE_DIRS})
    target_link_libraries(OpenCL_lib INTERFACE ${OpenCL_LIBRARIES})
    add_library(OpenCL::OpenCL ALIAS OpenCL_lib)
endif()
